local cropList = { 'NULL', --THIS IS NOT A VALID CROP
  'Acacia Bonzai',
  'Aluminum Oreberry',
  'Ardite Berry',
  'Argentia',
  'Artichoke',
  'aurelia',
  'Barley',
  'Bauxia',
  'Belladonna',
  'Berry',
  'Birch Bonzai',
  'Black Stonelilly',
  'Blackberry',
  'blackthorn',
  'Blazereed',
  'Blightberry',
  'Blue Glowshroom',
  'Blueberry',
  'Bobsyeruncleranks',
  'Brown Mushrooms',
  'brownMushroom',
  'Cactus',
  'carrots',
  'Chilly',
  'Cinderpearl',
  'Cobalt Berry',
  'cocoa',
  'coffee',
  'Copper Oreberry',
  'Coppon',
  'Corium',
  'Corpseplant',
  'Cotton',
  'Creeperweed',
  'Cucumber',
  'cyazint',
  'cyprium',
  'dandelion',
  'Dark Oak Bonzai',
  'Diareed',
  'Duskberry',
  'eatingplant',
  'Eggplant',
  'Ember Moss',
  'Enderbloom',
  'Essence Berry',
  'Evil Ore',
  'Eyebulb',
  'ferru',
  'Fertilia',
  'Flax',
  'Flowering Vines',
  'Galvania',
  'Garlic',
  'Garnydinia',
  'Glint Weed',
  'Glowflower',
  'Glowheat',
  'Glowing Earth Coral',
  'Glowshroom',
  'God of Thunder',
  'Gold Oreberry',
  'Goldfish Plant',
  'Grape',
  'Gray Stonelilly',
  'Green Glowshroom',
  'Hemp',
  'hops',
  'Huckleberry',
  'Indigo',
  'Iron Oreberry',
  'Ivy',
  'Jungle Bonsai',
  'Knightly Oreberry',
  'Lazulia',
  'Lemon',
  'Liveroots',
  'Magic Metal Berry',
  'Magical Nightshade',
  'Maloberry',
  'Mandragora',
  'Meatrose',
  'melon',
  'Milkwart',
  'Moss',
  'Nether Stonelilly',
  'netherWart',
  'Nickelback',
  'Oak Bonsai',
  'Oilberries',
  'Olivia',
  'Onion',
  'Papyrus',
  'Platina',
  'Plumbilia',
  'plumbiscus',
  'potato',
  'Primordial Berry',
  'pumpkin',
  'Purple Glowshroom',
  'Pyrolusium',
  'Quantaria',
  'Rape',
  'Raspberry',
  'Reactoria',
  'Red Mushrooms',
  'Red Stonelilly',
  'redMushroom',
  'redwheat',
  'reed',
  'rose',
  'Saguaro Cactus',
  'Salty Root',
  'Sapphirum',
  'Scheelinium',
  'Shimmerleaf',
  'shining',
  'Skyberry',
  'Slimeplant',
  'Snowbell',
  'Space Plant',
  'Spanish Moss',
  'Spidernip',
  'Spruce Bonsai',
  'stagnium',
  'Stargatium',
  'StarWart',
  'Steeleafranks',
  'stickreed',
  'Stingberry',
  'Strawberry',
  'Sugar Beet',
  'Tea',
  'Tearstalks',
  'terraWart',
  'Thornvines',
  'Tin Oreberry',
  'Tine',
  'Titania',
  'Tomato',
  'Transformium',
  'Trollplant',
  'tulip',
  'Turnip',
  'venomilia',
  'Vines',
  'Waterlilly',
  'wheat',
  'White Stonelilly',
  'Wild Carrots',
  'Withereed',
  "Wolf's Bane", --uses double quotes because the name contains an apostrophe
  'Yellow Stonelilly',
  'Zomplant'
}

--DO NOT CHANGE ANYTHING BEYOND THIS POINT, IT WILL SERIOUSLY MESS UP THE ROBOT (unless you know what you're doing)

--this array that will contain the information in all of the following arrays
local constants = {}

--contains the number of types of possible children (excluding itself, grass, and weed)
local possibleChildren = {67,55,57,80,92,79,55,40,94,82,67,57,77,64,79,83,91,77,7,68,45,77,49,108,107,58,83,59,95,77,77,17,38,108,66,98,66,67,5,81,70,81,102,15,52,44,63,97,3,67,82,50,92,72,90,82,8,95,91,41,55,99,107,61,91,73,108,79,74,55,75,67,46,11,108,22,59,2,77,93,83,74,86,86,62,98,84,74,6,71,107,94,49,82,96,49,1,71,91,33,39,108,77,37,33,61,47,88,50,66,98,103,97,37,107,79,81,66,95,7,97,60,67,97,35,29,11,92,83,77,66,111,82,81,76,60,82,40,108,6,5,65,51,39,71,73,48,58,49,46,94,61,9}
--contains the names of all the possible children (corresponding to the possibleChildren array)
local childrenNames = {}
--contains a boolean that determines if that possible child is an ore crop
local isOre = {}

--this loop fills out the 4d array with the parent crop, all possible child crops, how likely it is to be bred, and if it is an ore crop
for parent=1, #cropList do
  constants[parent] = cropList[parent]
  for child=1, possibleChildren[parent] do
    constants[parent][child] = 'filler' --placeholder
    constants[parent][child][1] = 0.0 --placeholder
    constants[parent][child][1][1] = false --placeholder
  end
end

return {
      cropList = cropList,
      constants = constants
}
