--This will be ordered alphebetically, with the exception of null
local cropList = {
  'NULL',
  'Acacia Bonzai',
  'Aluminum Oreberry',
  'Ardite Berry',
  'Argentia',
  'Artichoke',
  'aurelia',
  'Barley',
  'Bauxia',
  'Belladonna',
  'Berry',
  'Birch Bonzai',
  'Black Stonelilly'
  'Blackberry',
  'blackthorn',
  'Blazereed',
  'Blightberry',
  'Blue Glowshroom',
  'Blueberry',
  'Bobsyeruncleranks',
  'Brown Mushrooms',
  'brownMushroom',
  'Cactus',
  'carrots',
  'Chilly',
  'Cinderpearl',
  'Cobalt Berry',
  'cocoa',
  'coffee',
  'Copper Oreberry',
  'Coppon',
  'Corium',
  'Corpseplant',
  'Cotton',
  'Creeperweed',
  'Cucumber',
  'cyazint',
  'cyprium',
  'dandelion',
  'Dark Oak Bonzai',
  'Diareed',
  'Duskberry',
  'eatingplant',
  'Eggplant',
  'Ember Moss',
  'Enderbloom',
  'Essence Berry',
  'Evil Ore',
  'Eyebulb',
  'ferru',
  'Fertilia',
  'Flax',
  'Flowering Vines',
  'Galvania',
  'Garlic',
  'Garnydinia',
  'Glint Weed',
  'Glowflower',
  'Glowheat',
  'Glowing Earth Coral',
  'Glowshroom',
  'God of Thunder',
  'Gold Oreberry',
  'Goldfish Plant',
  'Grape',
  'Gray Stonelilly',
  'Green Glowshroom',
  'Hemp',
  'hops',
  'Huckleberry',
  'Indigo',
  'Iron Oreberry',
  'Ivy',
  'Jungle Bonsai',
  'Knightly Oreberry',
  'Lazulia',
  'Lemon',
  'Liveroots',
  'Magic Metal Berry',
  'Magical Nightshade',
  'Maloberry',
  'Mandragora',
  'Meatrose',
  'melon',
  'Milkwart',
  'Moss',
  'Nether Stonelilly',
  'netherWart',
  'Nickelback',
  'Oak Bonsai',
  'Oilberries',
  'Olivia',
  'Onion',
  'Papyrus',
  'Platina',
  'Plumbilia',
  'plumbiscus',
  'potato',
  'Primordial Berry',
  'pumpkin',
  'Purple Glowshroom',
  'Pyrolusium',
  'Quantaria',
  'Rape', --Also known as Canola outside of the game
  'Raspberry',
  'Reactoria',
  'Red Mushrooms',
  'Red Stonelilly',
  'redMushroom',
  'redwheat',
  'reed',
  'rose',
  'Saguaro Cactus',
  'Salty Root',
  'Sapphirum',
  'Scheelinium',
  'Shimmerleaf',
  'shining',
  'Skyberry',
  'Slimeplant',
  'Snowbell',
  'Space Plant',
  'Spanish Moss',
  'Spidernip',
  'Spruce Bonsai',
  'stagnium',
  'Stargatium',
  'StarWart',
  'Steeleafranks',
  'stickreed',
  'Stingberry',
  'Strawberry',
  'Sugar Beet',
  'Tea',
  'Tearstalks',
  'terraWart',
  'Thornvines',
  'Tin Oreberry',
  'Tine',
  'Titania',
  'Tomato',
  'Transformium',
  'Trollplant',
  'tulip',
  'Turnip',
  'venomilia',
  'Vines',
  'Waterlilly',
  'wheat',
  'White Stonelilly',
  'Wild Carrots',
  'Withereed',
  "Wolf's Bane", --uses double quotes because the name contains an apostrophe
  'Yellow Stonelilly',
  'Zomplant'
}

return cropList
